# Generated by Django 5.0.6 on 2024-05-23 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="udpated",
            new_name="updated",
        ),
    ]
